name = "gwbhj-server"
main = "edge-functions/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "GWBHJ_KV"
id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID"

[vars]
ED25519_PRIVATE_KEY = "REPLACE_WITH_PRIVATE_KEY_HEX"
ADMIN_KEY = "REPLACE_WITH_ADMIN_KEY"
